// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvoh6nUlOAJ_PCEaKl_szkb8xk4IcBrQ8',
    appId: '1:859855887043:web:64a799c2e0c643d299e076',
    messagingSenderId: '859855887043',
    projectId: 'grocery-app-6ddc9',
    authDomain: 'grocery-app-6ddc9.firebaseapp.com',
    storageBucket: 'grocery-app-6ddc9.appspot.com',
    measurementId: 'G-0RYK4DF2EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD02cuYdBy_fYP74ydS7TmWeHG10Mm95sQ',
    appId: '1:859855887043:android:cd3cebd2a375eb9499e076',
    messagingSenderId: '859855887043',
    projectId: 'grocery-app-6ddc9',
    storageBucket: 'grocery-app-6ddc9.appspot.com',
  );
}
